@ECHO OFF
PAUSE

ECHO 'STOPPING SERVER.......'
call pm2 stop liveeye-media-service
ECHO 'STEP COMPLETED'

ECHO 'REMOVING PROCESS FROM WINDOWS STARTUP.....'
call pm2 delete liveeye-media-service
ECHO 'STEP COMPLETED'

ECHO 'SAVING EMPTY LIST PROCESS.....'
call pm2 save
ECHO 'STEP COMPLETED'

ECHO 'CLEARNING DUMP FROM THE PROCESS LIST.....'
call pm2 cleardump
ECHO 'STEP COMPLETED'

PAUSE
cmd /k